# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

name: Validate Push Main

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Main CI
    uses: ./.github/workflows/ci-main.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      pages: write
    with:
      ref: ${{ github.sha }}
      python_publish: none
      rewrite_version: false
      run_documentation: true
    secrets: inherit