# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
#
# SPDX-License-Identifier: MPL-2.0

name: Push CI

on:
  workflow_dispatch:
    inputs:
      push_type:
        description: 'Publish mode for images'
        required: true
        type: choice
        #always nightly by default
        default: 'true'
        options:
          - 'true'
          - 'latest'
  # actual trigger should be:
  # push:
  #   branches:
  #     - main
  #     - master

jobs:
  build-and-publish:
    name: Build & Publish
    uses: ./.github/workflows/build-ci.yml
    with:
      # defaults to 'true' for regular merges, or 'latest' for releases/main releases
      push: ${{ inputs.push_type || 'true' }}
      #actual parameter should be something like ?? 
      #push: ${{ github.event.inputs.push_type || 'true' }}