# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
# SPDX-License-Identifier: MPL-2.0

name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: PR CI
    uses: ./.github/workflows/ci-main.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      python_publish: testpypi
      rewrite_version: true
      run_documentation: false
    secrets: inherit
  