name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: PR CI
    uses: ./.github/workflows/ci-main.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      image_tag: ${{ github.event.pull_request.head.sha }}
      python_publish: testpypi
      run_documentation: false
    secrets: inherit