# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, EONERC, RWTH Aachen University
#
# SPDX-License-Identifier: MPL-2.0

name: Push Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to test (e.g., v1.2.3)'
        required: false
        type: string
        default: 'v1.0.0-test'
  # push:
  #   tags:
  #     - 'v*'

jobs:
  push-version:
    name: Build & Push Version
    uses: ./.github/workflows/ci-build.yaml
    permissions:
      contents: read
      packages: write
    with:
      push: true
      rebuild_images: true
      version: ${{ inputs.version || github.ref_name }}
    secrets: inherit